"""Export engine — generate downloadable reports in multiple formats.

Supports: PDF (via reportlab or HTML), Markdown, JSON, CSV.
Each export includes summary + extraction + speakers in one artifact.
"""
from __future__ import annotations

import csv
import io
import json
import logging
from typing import Any, Dict, List

logger = logging.getLogger(__name__)


def export_json(job_id: str, intel: Dict[str, Any]) -> str:
    """Export full intelligence as formatted JSON."""
    return json.dumps({"job_id": job_id, "intelligence": intel}, indent=2, default=str)


def export_csv(job_id: str, intel: Dict[str, Any]) -> str:
    """Export segments as CSV."""
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow([
        "job_id", "timestamp", "topic", "sentiment", "risk", "risk_score",
        "objections", "decision_signals", "confidence", "transcript_excerpt",
    ])

    for seg in intel.get("segments", []):
        ext = seg.get("extraction", seg)
        writer.writerow([
            job_id,
            seg.get("timestamp_str", ""),
            ext.get("topic", ""),
            ext.get("sentiment", ""),
            ext.get("risk", ""),
            round(ext.get("risk_score", 0), 3),
            "; ".join(ext.get("objections", [])),
            "; ".join(ext.get("decision_signals", [])),
            round(ext.get("confidence", 0), 2),
            seg.get("transcript", "")[:200],
        ])

    return output.getvalue()


def export_markdown(job_id: str, intel: Dict[str, Any]) -> str:
    """Export as formatted Markdown report."""
    lines = [
        f"# DealFrame Report — {job_id}",
        "",
        f"**Duration**: {intel.get('duration_ms', 0) / 1000:.0f}s",
        f"**Overall Risk**: {intel.get('overall_risk_score', 0):.0%}",
        "",
        "## Segments",
        "",
    ]

    for i, seg in enumerate(intel.get("segments", [])):
        ext = seg.get("extraction", seg)
        ts = seg.get("timestamp_str", f"#{i}")
        lines.append(f"### [{ts}] {ext.get('topic', 'general')}")
        lines.append(f"- **Sentiment**: {ext.get('sentiment', 'neutral')}")
        lines.append(f"- **Risk**: {ext.get('risk', 'low')} ({ext.get('risk_score', 0):.0%})")

        obj = ext.get("objections", [])
        if obj:
            lines.append(f"- **Objections**: {'; '.join(obj)}")
        sig = ext.get("decision_signals", [])
        if sig:
            lines.append(f"- **Signals**: {'; '.join(sig)}")

        transcript = seg.get("transcript", "")
        if transcript:
            lines.append(f"- **Transcript**: {transcript[:300]}")
        lines.append("")

    # Speaker intelligence
    speaker_intel = intel.get("speaker_intelligence", {})
    if speaker_intel:
        lines.append("## Speaker Analytics")
        lines.append("")
        talk_ratio = speaker_intel.get("talk_ratio", {})
        for speaker, ratio in talk_ratio.items():
            lines.append(f"- **{speaker}**: {ratio:.0%} talk time")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by DealFrame*")
    return "\n".join(lines)


def export_html_report(job_id: str, intel: Dict[str, Any]) -> str:
    """Export as styled HTML report (for PDF conversion)."""
    segments = intel.get("segments", [])
    risk = intel.get("overall_risk_score", 0)

    seg_rows = ""
    for seg in segments:
        ext = seg.get("extraction", seg)
        ts = seg.get("timestamp_str", "")
        risk_color = "#e74c3c" if ext.get("risk_score", 0) > 0.65 else "#f39c12" if ext.get("risk_score", 0) > 0.3 else "#2ecc71"
        seg_rows += f"""
        <tr>
            <td>{ts}</td>
            <td>{ext.get('topic', '')}</td>
            <td>{ext.get('sentiment', '')}</td>
            <td style="color:{risk_color};font-weight:bold">{ext.get('risk_score', 0):.0%}</td>
            <td>{'; '.join(ext.get('objections', [])) or '-'}</td>
            <td>{'; '.join(ext.get('decision_signals', [])) or '-'}</td>
        </tr>"""

    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>DealFrame Report - {job_id}</title>
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, sans-serif; max-width: 900px; margin: 40px auto; padding: 0 20px; }}
h1 {{ color: #1a1a2e; border-bottom: 3px solid #6366f1; padding-bottom: 10px; }}
table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
th, td {{ padding: 8px 12px; text-align: left; border-bottom: 1px solid #eee; }}
th {{ background: #f8f9fa; font-weight: 600; }}
.metric {{ display: inline-block; padding: 8px 16px; margin: 4px; border-radius: 8px; background: #f0f0ff; }}
</style></head>
<body>
<h1>DealFrame Intelligence Report</h1>
<p><strong>Job ID:</strong> {job_id} | <strong>Duration:</strong> {intel.get('duration_ms', 0) / 1000:.0f}s</p>
<div class="metric">Overall Risk: <strong>{risk:.0%}</strong></div>
<div class="metric">Segments: <strong>{len(segments)}</strong></div>
<h2>Segment Analysis</h2>
<table>
<tr><th>Time</th><th>Topic</th><th>Sentiment</th><th>Risk</th><th>Objections</th><th>Signals</th></tr>
{seg_rows}
</table>
<hr><p><em>Generated by DealFrame</em></p>
</body></html>"""


EXPORTERS = {
    "json": export_json,
    "csv": export_csv,
    "markdown": export_markdown,
    "md": export_markdown,
    "html": export_html_report,
}


def export(job_id: str, intel: Dict[str, Any], format: str = "json") -> str:
    """Export intelligence in the requested format."""
    exporter = EXPORTERS.get(format.lower())
    if not exporter:
        raise ValueError(f"Unsupported format: {format}. Supported: {list(EXPORTERS.keys())}")
    return exporter(job_id, intel)
