"""add annotations and review_items tables

Revision ID: 8a3f470ff444
Revises: f30420a7a849
Create Date: 2026-03-21 20:43:39.099419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a3f470ff444'
down_revision: Union[str, Sequence[str], None] = 'f30420a7a849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('segment_index', sa.Integer(), nullable=False),
    sa.Column('start_word', sa.Integer(), nullable=False),
    sa.Column('end_word', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotations_job_id'), 'annotations', ['job_id'], unique=False)
    op.create_index(op.f('ix_annotations_label'), 'annotations', ['label'], unique=False)
    op.create_index(op.f('ix_annotations_uid'), 'annotations', ['uid'], unique=True)
    op.create_table('review_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=255), nullable=False),
    sa.Column('segment_index', sa.Integer(), nullable=False),
    sa.Column('extraction', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reviewer', sa.String(length=255), nullable=True),
    sa.Column('corrected_extraction', sa.JSON(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_items_job_id'), 'review_items', ['job_id'], unique=False)
    op.create_index(op.f('ix_review_items_status'), 'review_items', ['status'], unique=False)
    op.create_index(op.f('ix_review_items_uid'), 'review_items', ['uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_items_uid'), table_name='review_items')
    op.drop_index(op.f('ix_review_items_status'), table_name='review_items')
    op.drop_index(op.f('ix_review_items_job_id'), table_name='review_items')
    op.drop_table('review_items')
    op.drop_index(op.f('ix_annotations_uid'), table_name='annotations')
    op.drop_index(op.f('ix_annotations_label'), table_name='annotations')
    op.drop_index(op.f('ix_annotations_job_id'), table_name='annotations')
    op.drop_table('annotations')
    # ### end Alembic commands ###
